# Generated by Django 5.2.4 on 2025-07-08 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.TextField(default='')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(validators=[django.core.validators.MinLengthValidator(6, 'Minimum 6 digits')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Completed', 'Completed')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_app.user')),
            ],
        ),
    ]
